inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'test/dummy/**/*'
    - 'lib/**/templates/**/*'

# Offense count: 46
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Exclude:
    - 'test/dummy/**/*'
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoredPatterns:
    - '^\s*desc:\s.*'
  Max: 100

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 11
